-- ============================================================
-- Tabla: user_preferences
-- Guarda TODAS las preferencias visuales del mapa por usuario.
-- Reemplaza el localStorage actual para que las preferencias
-- persistan entre dispositivos y sesiones.
-- Ejecutar en Supabase SQL Editor.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.user_preferences (
  -- PK
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- FK al usuario (user.id del AuthContext — string alfanumérico)
  user_id         text NOT NULL,

  -- ═══════════════════════════════════════════════════════════
  -- 1. VISIBILIDAD DE CAPAS (eye toggles)
  -- ═══════════════════════════════════════════════════════════
  moviles_visible   boolean NOT NULL DEFAULT true,   -- ojo de móviles
  pedidos_visible   boolean NOT NULL DEFAULT true,   -- ojo de pedidos
  services_visible  boolean NOT NULL DEFAULT true,   -- ojo de services

  -- ═══════════════════════════════════════════════════════════
  -- 2. CAPA DE DATOS ACTIVA (DataViewMode)
  --    'normal' | 'distribucion' | 'demoras' | 'moviles-zonas'
  -- ═══════════════════════════════════════════════════════════
  data_view_mode    text NOT NULL DEFAULT 'normal',

  -- ═══════════════════════════════════════════════════════════
  -- 3. MAPA BASE
  --    'streets' | 'satellite' | 'terrain' | 'cartodb' | 'dark' | 'light'
  -- ═══════════════════════════════════════════════════════════
  default_map_layer text NOT NULL DEFAULT 'streets',

  -- ═══════════════════════════════════════════════════════════
  -- 4. ESTILO DE MARCADORES (tamaño visual)
  --    'normal' | 'compact' | 'mini'
  -- ═══════════════════════════════════════════════════════════
  movil_marker_style   text NOT NULL DEFAULT 'normal',
  pedido_marker_style  text NOT NULL DEFAULT 'normal',

  -- ═══════════════════════════════════════════════════════════
  -- 5. FORMA DE ICONOS (shape)
  --    'circle' | 'square' | 'triangle' | 'diamond' | 'hexagon' | 'star'
  -- ═══════════════════════════════════════════════════════════
  movil_shape    text NOT NULL DEFAULT 'circle',
  pedido_shape   text NOT NULL DEFAULT 'square',
  service_shape  text NOT NULL DEFAULT 'triangle',

  -- ═══════════════════════════════════════════════════════════
  -- 6. CLUSTERING
  -- ═══════════════════════════════════════════════════════════
  pedidos_cluster  boolean NOT NULL DEFAULT true,   -- agrupar pedidos/services

  -- ═══════════════════════════════════════════════════════════
  -- 7. ETIQUETAS / LABELS
  -- ═══════════════════════════════════════════════════════════
  show_demora_labels  boolean NOT NULL DEFAULT false,  -- mostrar minutos de demora

  -- ═══════════════════════════════════════════════════════════
  -- 8. REALTIME Y ACTIVIDAD
  -- ═══════════════════════════════════════════════════════════
  realtime_enabled          boolean NOT NULL DEFAULT true,
  show_active_moviles_only  boolean NOT NULL DEFAULT false,
  max_coordinate_delay_min  integer NOT NULL DEFAULT 30,    -- minutos para marcar inactivo

  -- ═══════════════════════════════════════════════════════════
  -- 9. ANIMACIONES / COMPLETADOS
  -- ═══════════════════════════════════════════════════════════
  show_route_animation    boolean NOT NULL DEFAULT true,
  show_completed_markers  boolean NOT NULL DEFAULT true,

  -- ═══════════════════════════════════════════════════════════
  -- METADATOS
  -- ═══════════════════════════════════════════════════════════
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

-- Un solo registro de preferencias por usuario
CREATE UNIQUE INDEX IF NOT EXISTS uq_user_preferences_user_id
  ON public.user_preferences (user_id);

-- Trigger para auto-actualizar updated_at
CREATE OR REPLACE FUNCTION public.fn_user_preferences_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_user_preferences_updated_at ON public.user_preferences;
CREATE TRIGGER trg_user_preferences_updated_at
  BEFORE UPDATE ON public.user_preferences
  FOR EACH ROW
  EXECUTE FUNCTION public.fn_user_preferences_updated_at();

-- ═══════════════════════════════════════════════════════════
-- RLS (Row Level Security) — opcional, activar si se usa
-- Supabase auth y se quiere que cada usuario vea solo lo suyo
-- ═══════════════════════════════════════════════════════════
-- ALTER TABLE public.user_preferences ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Users can manage own preferences"
--   ON public.user_preferences
--   USING (user_id = auth.uid()::text)
--   WITH CHECK (user_id = auth.uid()::text);

-- ═══════════════════════════════════════════════════════════
-- Permisos para service_role (usado desde Next.js API)
-- ═══════════════════════════════════════════════════════════
GRANT ALL ON public.user_preferences TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
